# Generated by Django 3.2.16 on 2022-11-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
