# Generated by Django 3.2.16 on 2022-11-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221101_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount',
        ),
        migrations.AddField(
            model_name='post',
            name='amount_money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
