# Generated by Django 3.2.16 on 2022-11-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221101_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount_money',
        ),
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
